baseURL = "https://remfi.netlify.app//"
languageCode = "en-us"
title = "REMFI"

relativeURLs = true
canonifyURLs = true

theme = "PaperMod"
themesDir = "themes"

[params]
  defaultTheme = "auto"

  [params.profileMode]
    enabled = true
    title = "REMFI"
    subtitle = "Renewable Energy Mechanical Failure Index"

    [[params.profileMode.buttons]]
      name = "Cases"
      url = "/cases/"

    [[params.profileMode.buttons]]
      name = "Methodology"
      url = "/methodology/"

    [[params.profileMode.buttons]]
      name = "Sources"
      url = "/sources/"

    [[params.profileMode.buttons]]
      name = "About"
      url = "/about/"
