baseURL = "https://remfiproject.org/"
languageCode = "en-us"
title = "REMFI"
theme = "PaperMod"

canonifyURLs = false
relativeURLs = false

[params.profileMode]
enabled = false


[params]
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = true

[menu]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Cases"
url = "/cases/"
weight = 2

[[menu.main]]
name = "Methodology"
url = "/methodology/"
weight = 3

[[menu.main]]
name = "About"
url = "/about/"
weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

